# Generated by Django 4.0.5 on 2022-06-04 01:24

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Recipient',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('birth_date', models.DateField()),
                ('email', models.EmailField(max_length=254)),
                ('relationship', models.CharField(choices=[(0, 'Select Relationship'), (1, 'Spouse'), (2, 'Parent'), (3, 'Sibling'), (4, 'Friend'), (5, 'Grandparent'), (6, 'Cousin'), (7, 'Coworker'), (1111, 'Add Relationship')], default=0, max_length=16)),
                ('gender', models.CharField(choices=[(0, 'Select Gender'), (1, 'Female'), (2, 'Male'), (3, 'Non-Binary')], default=0, max_length=10)),
                ('notes', models.TextField(max_length=256)),
                ('user_id', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('profile_image', models.URLField()),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
