# Generated by Django 4.0.5 on 2022-06-04 06:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gift_app', '0002_alter_recipient_options_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='recipient',
            name='gender',
            field=models.CharField(choices=[('Select', 'Select'), ('Female', 'Female'), ('Male', 'Male'), ('Non-Binary', 'Non-Binary')], default='select', max_length=10),
        ),
        migrations.AlterField(
            model_name='recipient',
            name='relationship',
            field=models.IntegerField(choices=[('Select', 'Select'), ('Spouse', 'Spouse'), ('Parent', 'Parent'), ('Sibling', 'Sibling'), ('Friend', 'Friend'), ('Grandparent', 'Grandparent'), ('Cousin', 'Cousin'), ('Coworker', 'Coworker'), ('Other', 'Other')], default='select', max_length=16),
        ),
    ]
