# Generated by Django 4.0.5 on 2022-06-04 06:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gift_app', '0003_alter_recipient_gender_alter_recipient_relationship'),
    ]

    operations = [
        migrations.AlterField(
            model_name='recipient',
            name='relationship',
            field=models.CharField(choices=[('Select', 'Select'), ('Spouse', 'Spouse'), ('Parent', 'Parent'), ('Sibling', 'Sibling'), ('Friend', 'Friend'), ('Grandparent', 'Grandparent'), ('Cousin', 'Cousin'), ('Coworker', 'Coworker'), ('Other', 'Other')], default='select', max_length=16),
        ),
    ]
