# Generated by Django 4.0.5 on 2022-06-05 21:39

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('gift_app', '0004_alter_recipient_relationship'),
    ]

    operations = [
        migrations.CreateModel(
            name='Occasion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('occasion_type', models.CharField(max_length=50)),
                ('repeat_yearly', models.BooleanField()),
                ('occasion_date', models.DateField()),
                ('description', models.TextField()),
                ('recipient', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='gift_app.recipient')),
            ],
            options={
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Gift',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=50)),
                ('description', models.TextField()),
                ('gift_type', models.CharField(max_length=50)),
                ('link', models.URLField()),
                ('occasion_id', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='gift_app.occasion')),
                ('recipient', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='gift_app.recipient')),
            ],
            options={
                'ordering': ['title'],
            },
        ),
    ]
