# Generated by Django 4.0.5 on 2022-06-09 00:46

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('gift_app', '0005_occasion_gift'),
    ]

    operations = [
        migrations.AlterField(
            model_name='gift',
            name='occasion_id',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='gift_app.occasion'),
        ),
        migrations.AlterField(
            model_name='gift',
            name='recipient',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='gift_app.recipient'),
        ),
        migrations.AlterField(
            model_name='occasion',
            name='repeat_yearly',
            field=models.BooleanField(default=False),
        ),
    ]
