# Generated by Django 4.0.5 on 2022-06-11 20:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gift_app', '0006_alter_gift_occasion_id_alter_gift_recipient_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='recipient',
            name='birth_date',
            field=models.DateField(blank=True),
        ),
        migrations.AlterField(
            model_name='recipient',
            name='email',
            field=models.EmailField(blank=True, max_length=254),
        ),
        migrations.AlterField(
            model_name='recipient',
            name='notes',
            field=models.TextField(blank=True),
        ),
    ]
