# Generated by Django 4.0.5 on 2022-06-11 21:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gift_app', '0007_alter_recipient_birth_date_alter_recipient_email_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='recipient',
            name='birth_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='recipient',
            name='email',
            field=models.EmailField(blank=True, max_length=254, null=True),
        ),
        migrations.AlterField(
            model_name='recipient',
            name='notes',
            field=models.TextField(blank=True, null=True),
        ),
    ]
