# Generated by Django 4.0.5 on 2022-06-12 01:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gift_app', '0008_alter_recipient_birth_date_alter_recipient_email_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='gift',
            name='given',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='gift',
            name='description',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='gift',
            name='link',
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='occasion',
            name='description',
            field=models.TextField(blank=True, null=True),
        ),
    ]
