# Generated by Django 4.0.5 on 2022-06-12 18:37

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('gift_app', '0009_gift_given_alter_gift_description_alter_gift_link_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='recipient',
            name='user_id',
        ),
        migrations.AddField(
            model_name='recipient',
            name='user',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
            preserve_default=False,
        ),
    ]
