# Generated by Django 4.0.5 on 2022-06-12 21:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('gift_app', '0015_gift_date_given_alter_recipient_user'),
    ]

    operations = [
        migrations.RenameField(
            model_name='gift',
            old_name='occasion_id',
            new_name='occasion',
        ),
    ]
