# Generated by Django 4.0.5 on 2022-06-19 17:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gift_app', '0017_gift_user_occasion_user'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='recipient',
            name='birth_date',
        ),
        migrations.AddField(
            model_name='recipient',
            name='age',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='recipient',
            name='birth_day',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='recipient',
            name='birth_month',
            field=models.IntegerField(choices=[(1, 'January'), (2, 'February'), (3, 'March'), (4, 'April'), (5, 'May'), (6, 'June'), (7, 'July'), (8, 'August'), (9, 'September'), (10, 'October'), (11, 'November'), (12, 'December')], default=1),
        ),
        migrations.AddField(
            model_name='recipient',
            name='birth_year',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='recipient',
            name='relationship',
            field=models.CharField(choices=[('Select', 'Select'), ('Spouse', 'Spouse'), ('Parent', 'Parent'), ('Child', 'Child'), ('Sibling', 'Sibling'), ('Friend', 'Friend'), ('Grandparent', 'Grandparent'), ('Cousin', 'Cousin'), ('Coworker', 'Coworker'), ('Other', 'Other')], default=1, max_length=16),
        ),
    ]
