# Generated by Django 4.0.5 on 2022-06-19 17:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gift_app', '0018_remove_recipient_birth_date_recipient_age_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='recipient',
            name='unknown_birthyear',
            field=models.BooleanField(default=False),
        ),
    ]
