# Generated by Django 4.0.5 on 2022-06-19 17:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('gift_app', '0019_recipient_unknown_birthyear'),
    ]

    operations = [
        migrations.RenameField(
            model_name='recipient',
            old_name='unknown_birthyear',
            new_name='birth_year_unknown',
        ),
    ]
