# Generated by Django 4.0.5 on 2022-06-23 17:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gift_app', '0021_alter_occasion_options_remove_occasion_name_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='gift',
            name='recipient',
        ),
        migrations.AlterField(
            model_name='occasion',
            name='occasion_type',
            field=models.CharField(choices=[('Birthday', 'Birthday'), ('Wedding Anniversary', 'Wedding Anniversary'), ('Wedding Anniversary', 'Dating Anniversary'), ('Work Anniversary', 'Work Anniversary'), ('Friendship Anniversary', 'Friendship Anniversary'), ("Mother's Day", "Mother's Day"), ("Father's Day", "Father's Day"), ('Graduation', 'Graduation'), ('Baby Shower', 'Baby Shower'), ('New Baby', 'New Baby'), ('Wedding', 'Wedding'), ('House Warming', 'House Warming'), ('Thanks', 'Thanks'), ('Christmas', 'Christmas'), ('Easter', 'Easter'), ('Chinese New Year', 'Chinese New Year'), ("Valentine's Day", "Valentine's Day"), ('Just Because', 'Just Because'), ('Other', 'Other')], default='Birthday', max_length=50),
        ),
    ]
