# Generated by Django 4.0.5 on 2022-07-20 03:14

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('gift_app', '0022_remove_gift_recipient_alter_occasion_occasion_type'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='occasion',
            options={'ordering': ['recipient__last_name']},
        ),
        migrations.RemoveField(
            model_name='recipient',
            name='email',
        ),
        migrations.AddField(
            model_name='gift',
            name='created_on',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='gift',
            name='updated_on',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name='occasion',
            name='created_on',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='occasion',
            name='updated_on',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name='recipient',
            name='created_on',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='recipient',
            name='updated_on',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AlterField(
            model_name='occasion',
            name='occasion_type',
            field=models.CharField(choices=[('Birthday', 'Birthday'), ('Wedding Anniversary', 'Wedding Anniversary'), ('Dating Anniversary', 'Dating Anniversary'), ('Work Anniversary', 'Work Anniversary'), ("Mother's Day", "Mother's Day"), ("Father's Day", "Father's Day"), ("Valentine's Day", "Valentine's Day")], default='Birthday', max_length=50),
        ),
        migrations.AlterField(
            model_name='recipient',
            name='gender',
            field=models.CharField(choices=[('Select', 'Select'), ('Female', 'Female'), ('Male', 'Male'), ('Non-Binary', 'Non-Binary')], default='Select', max_length=10),
        ),
        migrations.AlterField(
            model_name='recipient',
            name='relationship',
            field=models.CharField(choices=[('Select', 'Select'), ('Spouse', 'Spouse'), ('Parent', 'Parent'), ('Child', 'Child'), ('Sibling', 'Sibling'), ('Friend', 'Friend'), ('Grandparent', 'Grandparent'), ('Cousin', 'Cousin'), ('Coworker', 'Coworker'), ('Other', 'Other')], default='Select', max_length=16),
        ),
    ]
