# Generated by Django 4.0.5 on 2022-08-01 16:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gift_app', '0025_alter_recipient_relationship'),
    ]

    operations = [
        migrations.AlterField(
            model_name='recipient',
            name='age',
            field=models.IntegerField(default=None),
            preserve_default=False,
        ),
    ]
