# Generated by Django 4.0.5 on 2022-08-01 16:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gift_app', '0025_alter_recipient_relationship'),
    ]

    operations = [
        migrations.AlterField(
            model_name='recipient',
            name='age',
            field=models.IntegerField(default=40),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='recipient',
            name='birth_month',
            field=models.IntegerField(choices=[(1, 'January'), (2, 'February'), (3, 'March'), (4, 'April'), (5, 'May'), (6, 'June'), (7, 'July'), (8, 'August'), (9, 'September'), (10, 'October'), (11, 'November'), (12, 'December')], default=0),
        ),
        migrations.AlterField(
            model_name='recipient',
            name='gender',
            field=models.CharField(choices=[('Female', 'Female'), ('Male', 'Male'), ('Non-Binary', 'Non-Binary')], default='Female', max_length=10),
        ),
        migrations.AlterField(
            model_name='recipient',
            name='relationship',
            field=models.CharField(choices=[('Friend', 'Friend'), ('Spouse', 'Spouse'), ('Parent', 'Parent'), ('Aunt', 'Aunt'), ('Uncle', 'Uncle'), ('Child', 'Child'), ('Sibling', 'Sibling'), ('Grandparent', 'Grandparent'), ('Cousin', 'Cousin'), ('Coworker', 'Coworker'), ('Other', 'Other')], default='Friend', max_length=16),
        ),
    ]
