# Generated by Django 4.0.5 on 2022-08-01 16:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gift_app', '0026_alter_recipient_age'),
    ]

    operations = [
        migrations.AlterField(
            model_name='recipient',
            name='birth_day',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='recipient',
            name='birth_month',
            field=models.PositiveIntegerField(choices=[(0, 'Select'), (1, 'January'), (2, 'February'), (3, 'March'), (4, 'April'), (5, 'May'), (6, 'June'), (7, 'July'), (8, 'August'), (9, 'September'), (10, 'October'), (11, 'November'), (12, 'December')], default=0),
        ),
        migrations.AlterField(
            model_name='recipient',
            name='birth_year',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
    ]
